" git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

" Vundle
filetype off				        " required
set rtp+=~/.vim/bundle/Vundle.vim 	" runtime path initialize vundle
call vundle#begin()			        " call vundle#begin('~/some/path/here')


" Plugins
Plugin 'VundleVim/Vundle.vim'		" required
Plugin 'ctrlpvim/ctrlp.vim'		    " find files

Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

Plugin 'scrooloose/syntastic'

Plugin 'dracula/vim'
Plugin 'joshdick/onedark.vim'
Plugin 'sjl/badwolf'

call vundle#end()            		" required
filetype plugin indent on    		" required



set nocompatible			" be iMproved, required
syntax on
set nowrap				    " ?????
set encoding=utf8

" lines
set number relativenumber

" tabs
set tabstop=4
set shiftwidth=4
set smarttab
set expandtab

" status line
set laststatus=2            " ???

" cursor
set cursorline              " highlight current

" theme
color badwolf

:let mapleader = "\e"


" CtrlP
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows

let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(exe|so|dll)$',
  \ 'link': 'some_bad_symbolic_links',
  \ }

" Vim-Airline Configuration
let g:airline#extensions#tabline#enabled = 1

" KeyMaps
:map <leader>b :CtrlPBuffer<CR>

